name: Updater

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

permissions:
  contents: read

env:
  CF_DEST_URL: ${{ secrets.CF_DEST_URL }}
  CF_UPSTREAM_UPLOAD_URL: ${{ secrets.CF_UPSTREAM_UPLOAD_URL }}
  CF_NOTIFY_URL: ${{ secrets.CF_NOTIFY_URL }}
  CF_PROXY_SERVER: ${{ secrets.CF_PROXY_SERVER }}

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Run Container
        uses: vanish-man/cf-cheer@master
